/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TopStudentsRouteImport } from './routes/top-students'
import { Route as StudentsRouteImport } from './routes/students'
import { Route as StatisticsRouteImport } from './routes/statistics'
import { Route as IndexRouteImport } from './routes/index'

const TopStudentsRoute = TopStudentsRouteImport.update({
  id: '/top-students',
  path: '/top-students',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentsRoute = StudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => rootRouteImport,
} as any)
const StatisticsRoute = StatisticsRouteImport.update({
  id: '/statistics',
  path: '/statistics',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/statistics': typeof StatisticsRoute
  '/students': typeof StudentsRoute
  '/top-students': typeof TopStudentsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/statistics': typeof StatisticsRoute
  '/students': typeof StudentsRoute
  '/top-students': typeof TopStudentsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/statistics': typeof StatisticsRoute
  '/students': typeof StudentsRoute
  '/top-students': typeof TopStudentsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/statistics' | '/students' | '/top-students'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/statistics' | '/students' | '/top-students'
  id: '__root__' | '/' | '/statistics' | '/students' | '/top-students'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  StatisticsRoute: typeof StatisticsRoute
  StudentsRoute: typeof StudentsRoute
  TopStudentsRoute: typeof TopStudentsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/top-students': {
      id: '/top-students'
      path: '/top-students'
      fullPath: '/top-students'
      preLoaderRoute: typeof TopStudentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/students': {
      id: '/students'
      path: '/students'
      fullPath: '/students'
      preLoaderRoute: typeof StudentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/statistics': {
      id: '/statistics'
      path: '/statistics'
      fullPath: '/statistics'
      preLoaderRoute: typeof StatisticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  StatisticsRoute: StatisticsRoute,
  StudentsRoute: StudentsRoute,
  TopStudentsRoute: TopStudentsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
